import Head from 'next/head'
import styled from 'styled-components';

import {
  MaxWidth,
  Container
} from '../components/ui'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MaxWidth>
        <h1>
          Welcome to the Wildflowers directory!
        </h1>

        <Container>
          here is a styled container!
        </Container>

      </MaxWidth>
    </div>
  )
}
