import Head from 'next/head'
import styled from 'styled-components';

const MaxWidth = styled.div`
  max-width: ${({ theme }) => theme.breakpoint.lg}px;
  margin: ${({ theme }) => theme.util.buffer*10}px auto;
`;

const StyledContainer = styled.div`
  padding: ${({ theme }) => theme.util.buffer*4}px;
  border-radius: ${({ theme }) => theme.util.radiusLarge}px;
  box-shadow: ${({ theme }) => theme.util.shadowLarge};
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MaxWidth>
        <h1>
          Welcome to the Wildflowers directory!
        </h1>

        <StyledContainer>
          here is a styled container!
        </StyledContainer>

      </MaxWidth>
    </div>
  )
}
