import Head from 'next/head'
import styled from 'styled-components';

import {
  MaxWidth,
  Container,
  Text,
  Button
} from '../components/ui'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wildflower Schools | Directory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MaxWidth>

        <Container>
          <Text title large bold>
            Brooklyn Heights Montessori
          </Text>
        </Container>

        <Button primary lightened>Contact Maya</Button>

      </MaxWidth>
    </div>
  )
}
